#page title
page_title                                : Top2000                                   # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : nl                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.microsoft.com/store/detail/top-2000/9WZDNCRDR106?hl=nl-nl&gl=nl                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.chroomsoft.top2000&gl=NL                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Top 2000                                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : De volledige Top 2000 op uw smartphone

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Rick Neeft                               
your_link                                 : https://www.rickneeft.dev/about
your_city                                 :                                 
email_address                             : rick.neeft@outlook.com
facebook_username                         : top2000app                                          
instagram_username                        : 
twitter_username                          : rneeft
github_username                           : rneeft
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Alle edities sinds 1999
    description                           : Ga terug in de tijd en bekijk elke editie vanaf 1999 tot en met de laatste
    fontawesome_icon_name                 : list-ol
    
  - title                                 : Ontdek Per uur
    description                           : Bekijk de lijst per uur en navigeer tussen uren
    fontawesome_icon_name                 : clock

  - title                                 : Live view
    description                           : Tijdens de Top 2000 op de radio bekijkt u live per uur mee in de app
    fontawesome_icon_name                 : tower-cell

  - title                                 : Zoek!
    description                           : Zoek in de app naar uw favoriete artiest, track of jaar.
    fontawesome_icon_name                 : magnifying-glass

  - title                                 : Eén handig overzicht
    description                           : Alle informatie over een track in één handig overzicht.
    fontawesome_icon_name                 : circle-info
  
  - title                                 : Youtube
    description                           : Bekijk uw favoriete track snel in Youtube met de handige integratie
    fontawesome_icon_name                 : brands fa-youtube

  - title                                 : Donker & licht thema
    description                           : Keuze uit een donker en licht thema
    fontawesome_icon_name                 : circle-half-stroke

  - title                                 : Gratis en géén reclame
    description                           : De app is en blijft gratis en bevat geen enkele reclame!
    fontawesome_icon_name                 : handshake

  - title                                 : Nederlands/ English ou Français
    description                           : Dutch not your main language? Change it to English 'ou Français?'
    fontawesome_icon_name                 : language

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
